config/routes.rb
Influence::Application.routes.draw do
	devise_for :users
	resources :users
  resources :ambassadors do
    resources :impressions
    resources :leads
  end
  get '/ongoing_list', to: 'ambassadors#ongoing_list'
  get '/ambassadors/campaigns', to: 'ambassadors#campaigns'
  get '/instagram_redirect', to: 'ambassadors#instagram_redirect', as: :instagram_redirect

  get '/users/sign_in?role=influencer', to: 'devise/sessions#new'
  get '/brand_list', to: 'brands#brand_list'
  resources :brands do

    resources :campaigns do
      get '/invite', to: 'campaigns#invite'
      get '/stats', to: 'campaigns#stats'
    end
  end

  root :to => 'home#index'
end

app/models/ambassador.rb
class Ambassador < ActiveRecord::Base
  attr_accessible :user_id, :campaign_id, :status
  belongs_to :user
  belongs_to :campaign
  has_many   :leads
  has_many   :impressions
  has_many   :ambassador_requests
end

app/controllers/ambassadors_controller.rb
class AmbassadorsController < ApplicationController
  layout false
  def index
    if (!current_user)
      redirect_to "/"
    end
    @ambassadors = Ambassador.where(user_id: current_user.id, status: 'accepted');
    @user_id = params[:user_id];

    if current_user.socials.count > 0
      if current_user.socials.where(provider: "instagram").where("followers <> ''")
        client = current_user.socials.where(provider: "instagram").first
        uid = client.uid.to_i
        if (current_user.socials.where(provider: "instagram").first.access_token)
          access_token = current_user.socials.where(provider: "instagram").first.access_token
          response2 = HTTParty.get("https://api.instagram.com/v1/users/#{uid}/?access_token=#{access_token}");
          client.followers = response2['data']['counts']['followed_by']
          client.save
        end
      end
    end
  end

  def new
  end

  def create
    @ambassador = Ambassador.new(ambassador_param)
    if @ambassador.save
      respond_to do |format|
        format.js
      end
    else
      head :bad_request
    end
  end

  def show
    @invites = Ambassador.where(user_id: current_user, status: 'pending')
    render "ambassadors/campaigns"
  end

  def update
    @ambassador = Ambassador.find(params[:id])
    @action = params[:status]
    if @ambassador.update_attributes(status: @action)
      respond_to do |format|
        format.js
      end
    end
  end

  def ongoing_list
    @ambassadors = Ambassador.where(user_id: current_user, status: 'accepted')
    respond_to do |format|
      format.js
    end
  end

  def instagram_redirect
    options = {
      body: {
        client_id: 'fdaf0607c4c04ac5b0dd5c2e30f56fd3',
        client_secret: '2632323495fc4e2ea569dba394853736',
        grant_type: 'authorization_code',
        redirect_uri: 'http://swayup.herokuapp.com/instagram_redirect',
        code: params[:code]
      }
    }

  response = HTTParty.post('https://api.instagram.com/oauth/access_token', options)
  
  social = Social.new
    social.provider = "instagram"
    social.user_id = current_user.id
    social.access_token = response['access_token']
    social.uid = response['user']['id']
    social.username = response['user']['username']
    social.bio = response['user']['bio']
    social.photo = response['user']['profile_picture']
    social.full_name = response['user']['full_name']

    current_user.socials << social

    #current_user.save
    redirect_to ambassadors_path
  end

  private
    def ambassador_param
      params.require(:ambassador).permit(:user_id, :campaign_id, :status)
    end
end

app/helpers/ambassadors_helper.rb
module AmbassadorsHelper
end

app/views/ambassadors/_instagram_stat.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!-- Tnstagram Stats -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title-box">
          <h3>Your Instagram Stats</h3>
          <span>Details</span>
        </div>
      </div>
      <div class="panel-body padding-0">
        <div class="chart-holder" id="dashboard-line-1" style="height: 200px;">
          <% if !ig_user.blank? %>
              <div class="text">
                <h4 class="text-center">Instagram handle: <%= ig_user.username %></h4>
                <h4 class="text-center">Number of followers: <%= ig_user.followers %></h4>
              </div>
          <% end %>
        </div>
      </div>
    </div>
    <!-- END  Tnstagram Stats-->
  </div>
</div>
</div>

app/views/ambassadors/_invite.html.erb
<div class="page-content-wrap">
  <% if current_user.socials.where(provider: "instagram").empty? %>
      <div class="row text-center">
        <a href="https://api.instagram.com/oauth/authorize/?client_id=fdaf0607c4c04ac5b0dd5c2e30f56fd3&redirect_uri=http://localhost:3000/instagram_redirect&response_type=code" class="btn btn-primary btn-lg" style="background-color: #125688;"><i class="fa fa-instagram"></i> Add Instagram Account</a>
      </div>
      <br >
      <div class="alert alert-warning text-center">
        <strong>Whoops!</strong>You can't accept any invites until you add your Instagram account
      </div>
  <% elsif !@invites.empty? %>
      <div class="alert alert-info text-center">
        <strong>Whoop whoop! </strong>Brands want you. You should be proud :)
      </div>
  <% elsif @invites.empty? %>
      <div class="alert alert-info text-center">
        You don't have any invites yet
      </div>
  <% end %>

  <div class="row">
    <% if !@invites.empty? %>
        <% @invites.each do |amb| %>
            <div id="amb_card_<%= amb.id %>" class="col-lg-4 card">
              <div class="col-sm-4 cinvite">
                <%= image_tag amb.campaign.image.url %>
              </div>
              <div class="col-sm-8">
                <h3 class="text-center"><%= amb.campaign.brand.name %></h3>
                <h2 class="text-center"><%= amb.campaign.name %></h2>
                <div class="row">
                  <% if current_user.socials.where(provider: "instagram").empty? %>
                      <button class="btn btn-success disabled">Accept</button>
                      <button class="btn btn-danger disabled">Decline</button>
                  <% else %>
                      <%= link_to  ambassador_path(amb, status: 'accepted'), method: :put, remote: true do %>
                          <div class="col-xs-6 invite-but">
                            <i class='fa fa-check'></i>
                          </div>
                      <% end %>
                      <%= link_to  ambassador_path(amb, status: 'rejected'), method: :put, remote: true do %>
                          <div class="col-xs-6 invite-but red">
                            <i class='fa fa-close'></i>
                          </div>
                      <% end %>
                  <% end %>
                </div>
              </div>

            </div>
        <% end %>
    <% end %>

  </div>

</div>

app/views/ambassadors/_ongoing.html.erb
Ongoing
<hr>
<% @ambassadors.each do |amb| %>
    <%= link_to "/brands/#{amb.campaign.brand_id}/campaigns/#{amb.campaign.id}", remote: true do %>
        <div class="card">
          <h3 class="text-center"><%= amb.campaign.brand.name %></h3>
          <h2 class="text-center"><%= amb.campaign.name %></h2>
        </div>
    <% end %>
<% end %>

app/views/ambassadors/_sidebar.html.erb
<script type="text/javascript">
            $( document ).ready(function(){
               $(".x-navigation").on('click', function(){
                if($("li").hasClass()){
                    $("li").removeClass();
                }
                $(this).addClass("active");
                //$(".page-container").toggleClass("page-navigation-toggled page-container-wide");

                });
            });
        </script> 
<div class="page-sidebar">
                <!-- START X-NAVIGATION -->
                <% ig_user = current_user.socials.where(provider: "instagram").first %>
                <ul class="x-navigation">
                    <li class="xn-logo">
                        <a href="index.html">Sway Up</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <% if current_user.socials.where(provider: "instagram").blank? %>
                                <%= image_tag('blank-user.png') %>
                            <% else %>
                                <%= image_tag(ig_user.photo, alt: "Your profile photo") %> 
                            <% end %>
                            
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                            <% if current_user.socials.where(provider: "instagram").blank? %>
                                <%= image_tag('blank-user.png') %>
                            <% else %>
                                <%= image_tag(current_user.socials.where(provider: "instagram").first.photo) %>
                            <% end %>
                                
                            </div>
                            <div class="profile-data">
                            <div class="profile-data-name"><%= current_user.email %></div>
                            <% if !current_user.socials.where(provider: "instagram").blank? %>
                                <div class="profile-data-title"><%= ig_user.bio %></div>
                            <% end %>
                            </div>
                            <div class="profile-controls">
                                <a href="pages-profile.html" class="profile-control-left"><span class="fa fa-info"></span></a>
                            </div>
                        </div>                                                                        
                    </li>
                    <li class="active">
                        <%= link_to ambassadors_path do%>
                            <span class="fa fa-desktop"></span> <span class="xn-text">Dashboard</span>
                        <% end %>
                    </li>                    
                    
                    <li>
                        <%= link_to ambassadors_campaigns_path do%>
                            <span class="fa fa-bell"></span> <span class="xn-text">View Campaigns Invites</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to ongoing_list_path, remote: true do%>
                            <span class="fa fa-clock-o"></span> <span class="xn-text">Ongoing Campaigns</span>
                        <% end %>
                    </li>
                </ul>
                <!-- END X-NAVIGATION -->
            </div>

app/views/ambassadors/_topbar.html.erb
<!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SEARCH -->
                    <li class="xn-search">
                        <form role="form">
                            <input type="text" name="search" placeholder="Search..."/>
                        </form>
                    </li>   
                    <!-- END SEARCH -->
                    <!-- SIGN OUT -->
                    <li class="pull-right">
                        <%= link_to destroy_user_session_path, method: :delete do%>
                            <i class="fa fa-sign-out"></i>Sign Out</a>
                        <% end %>                        
                    </li> 
                    <!-- END SIGN OUT -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->      

app/views/ambassadors/campaigns.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>        
        <!-- META SECTION -->
        <title>Sway Up</title>            
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>      
  	    <link rel="stylesheet" href="../assets/theme-default.css.scss">
  		<style type="text/css">
		  .x-navigation.x-navigation-minimized {
		  min-height: 670px!important;
		}
  		</style>
  		<script type="text/javascript">
  		    $( document ).ready(function(){
  			   $(".xn-icon-button").on('click', function(){
  			   $(".page-sidebar .x-navigation").toggleClass("x-navigation-minimized");
  			   $(".page-container").toggleClass("page-navigation-toggled page-container-wide");
  				});
            });
  		</script>     
    </head>
    <body>
        <!-- START PAGE CONTAINER -->
        <div class="page-container">
            
            <!-- START PAGE SIDEBAR -->
            <%= render 'sidebar.html.erb'%>
            <!-- END PAGE SIDEBAR -->
            
            <!-- PAGE CONTENT -->
            <div class="page-content">
            <%= render 'topbar.html.erb'%>
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><a href="#">Home</a></li>                    
                    <li class="active">View Campaigns</li>
                </ul>
                <!-- END BREADCRUMB -->                       
                
                <!-- PAGE CONTENT WRAPPER -->
                <div id="content">
                    <section>
                        <div class="section-body">
                            <%= render 'invite' %>
                        </div>
                    </section>
                </div>
                <!-- END PAGE CONTENT WRAPPER -->                                
            </div>            
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->                 
        
    </body>
</html>

app/views/ambassadors/create.js.erb
$('#user_card_<%= @ambassador.user_id %>').addClass('c-inactive');
$('#user_card_<%= @ambassador.user_id %> button').prop('disabled', true);

app/views/ambassadors/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>        
        <!-- META SECTION -->
        <title>Sway Up</title>            
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>      
  	    <!--<link rel="stylesheet" href="assets/theme-default.css.scss">-->
  		<style type="text/css">
		  .x-navigation.x-navigation-minimized {
		  min-height: 670px!important;
		}
  		</style>
  		<script type="text/javascript">
  		    $(document).ready(function(){
  			   $(".xn-icon-button").on('click', function(){
  			       $(".page-sidebar .x-navigation").toggleClass("x-navigation-minimized");
  			       $(".page-container").toggleClass("page-navigation-toggled page-container-wide");
  				});

               if(<%= current_user.socials.where(provider: "instagram").empty? %>){
                    console.log("blank, so modal appears");
                    setTimeout(function(){
                        $('#myModal').modal('show');
                    }, 2000);
                    $.cookie('msg', 'shown', {expires: 1000});
                    
                }
                else{
                    console.log("user has signed in, modal doesnt appear");
                    $("div#myModal.modal").css('display','none');
                } 
            });
  		</script>     
    </head>
    <body>
        <!-- START PAGE CONTAINER -->
        <div class="page-container">
            <!-- Current user's instagram details -->
            <% ig_user = current_user.socials.where(provider: "instagram").first %>
            <!-- START PAGE SIDEBAR -->
            <%= render 'sidebar.html.erb'%>
            <!-- END PAGE SIDEBAR -->
            
            <!-- PAGE CONTENT -->
            <div class="page-content">                    
            <%= render 'topbar.html.erb'%>
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><a href="#">Home</a></li>                    
                    <li class="active">Dashboard</li>
                </ul>
                <!-- END BREADCRUMB -->                       
                
                <!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap"> 
                    <!-- START WIDGETS -->                    
                    <div class="row">
                        <% if current_user.socials.where(provider: "instagram").empty? %>
                        <div class="row text-center">
                                <a href="https://api.instagram.com/oauth/authorize/?client_id=fdaf0607c4c04ac5b0dd5c2e30f56fd3&redirect_uri=http://swayup.herokuapp.com/instagram_redirect&response_type=code" class="btn btn-primary btn-lg" style="background-color: #125688;"><i class="fa fa-instagram"></i> Add Instagram Account</a>
                            </div>
                            <br >
                        <% end %>
                        <div class="col-md-3">
                            <!-- START WIDGET MESSAGES -->
                            <div class="widget widget-default widget-item-icon">
                                <div class="widget-item-left">
                                    <span class="fa fa-hourglass-half"></span>
                                </div>                             
                                <div class="widget-data">
                                    <div class="widget-int num-count"><%= @ambassadors.size %></div>
                                    <div class="widget-title">Ongoing Campaigns </div>
                                    <div class="widget-subtitle">You are involved in</div>
                                </div>      
                               
                            </div>                            
                            <!-- END WIDGET MESSAGES -->
                            
                        </div>
                        <div class="col-md-3">
                            <!-- START WIDGET MESSAGES -->
                            <div class="widget widget-default widget-item-icon">
                                <div class="widget-item-left">
                                    <span class="fa fa-hashtag"></span>
                                </div>                             
                                <div class="widget-data">
                                    <div class="widget-int num-count"><%= @ambassadors.size %></div>
                                    <div class="widget-title">Brands</div>
                                    <div class="widget-subtitle">You have advertised for</div>
                                </div>      
                               
                            </div>                            
                            <!-- END WIDGET MESSAGES -->
                            
                        </div>
                        <div class="col-md-3">
                            
                            <!-- START WIDGET REGISTRED -->
                            <div class="widget widget-default widget-item-icon" onclick="location.href='pages-address-book.html';">
                                <div class="widget-item-left">
                                    <span class="fa fa-money"></span>
                                </div>
                                <div class="widget-data">
                                    <div class="widget-int num-count"><%= @ambassadors.size * 15 %></div>
                                    <div class="widget-title">Amount of Money</div>
                                    <div class="widget-subtitle">You have earned</div>
                                </div>                           
                            </div>                            
                            <!-- END WIDGET REGISTRED -->
                            
                        </div>
                        <div class="col-md-3">
                            
                            <!-- START WIDGET CLOCK -->
                            <div class="widget widget-danger widget-padding-sm">
                                <div class="widget-big-int plugin-clock">00:00</div>                            
                                <div class="widget-subtitle plugin-date">Loading...</div>
                                <div class="widget-controls">                                
                                </div>                            
                                                       
                            </div>                        
                            <!-- END WIDGET CLOCK -->
                            
                        </div>
                    </div>
                    <!-- END WIDGETS -->
                  <div id="content">
                    <section>
                      <div class="section-body">
                        <%= render 'instagram_stat', ig_user: ig_user %>
                      </div>
                    </section>
                  </div>

                </div>
                <!-- END PAGE CONTENT WRAPPER -->                                
            </div>            
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->

        <!-- MESSAGE BOX-->
        <div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">You have to do this before you proceed</h4>
                    </div>
                    <div class="modal-body">
                        <div class="panel-body">
                            <div class="row text-center">
                                <a href="https://api.instagram.com/oauth/authorize/?client_id=fdaf0607c4c04ac5b0dd5c2e30f56fd3&redirect_uri=http://swayup.herokuapp.com/instagram_redirect&response_type=code" class="btn btn-primary btn-lg" style="background-color: #125688;"><i class="fa fa-instagram"></i> Add Instagram Account</a>
                            </div>
                            <h1 class="text-center ">OR</h1>
                            <h3 class="text-center">Enter your blog url</h3><br />
                            <form class="form-group">
                                <input type="text" value="http://" class="validate[required,custom[url]] form-control" id="form-validation-field-0">
                                <div class="text-center" style="margin-top:20px;">
                                    <button type="submit" class="btn btn-primary" style="background-color: #286090;">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <!-- END MESSAGE BOX-->
        <script src="assets/moment.min.js"></script>
        <script type="text/javascript">
            
        </script>
    </body>
</html>

app/views/ambassadors/new.html.erb
<h1>Ambassadors#new</h1>
<p>Find me in app/views/ambassadors/new.html.erb</p>

app/views/ambassadors/ongoing_list.js.erb
$("#content section .section-body").html("<%= escape_javascript(render 'ambassadors/ongoing') %>")

app/views/ambassadors/update.js.erb
$("#amb_card_<%= @ambassador.id %>").html("<%= @action +' '+@ambassador.campaign.name.capitalize %>")
        .delay(2000).hide("slow");