config/routes.rb
Influence::Application.routes.draw do
	devise_for :users
	resources :users
  resources :ambassadors do
    resources :impressions
    resources :leads
  end
  get '/ongoing_list', to: 'ambassadors#ongoing_list'
  get '/ambassadors/campaigns', to: 'ambassadors#campaigns'
  get '/instagram_redirect', to: 'ambassadors#instagram_redirect', as: :instagram_redirect

  get '/users/sign_in?role=influencer', to: 'devise/sessions#new'
  get '/brand_list', to: 'brands#brand_list'
  resources :brands do

    resources :campaigns do
      get '/invite', to: 'campaigns#invite'
      get '/stats', to: 'campaigns#stats'
    end
  end

  root :to => 'home#index'
end

app/models/ambassador.rb
class Ambassador < ActiveRecord::Base
  attr_accessible :user_id, :campaign_id, :status
  belongs_to :user
  belongs_to :campaign
  has_many   :leads
  has_many   :impressions
  has_many   :ambassador_requests
end

app/models/ambassador_request.rb
class AmbassadorRequest < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :ambassador
  belongs_to :campaign
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true
  validates :description,  presence: true

  has_many :campaigns
  belongs_to :user

  attr_accessible :name, :description
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :brand
  has_many :ambassadors
  has_and_belongs_to_many :countries
  belongs_to :interest
  has_many   :ambassador_requests
  has_many :impressions, through: :ambassadors
  mount_uploader :image, ImageUploader
  has_many :instagram_posts

  attr_accessible :name, :description, :url, :country_ids, :interest, :image, :tag

  def save_data_from_api
    min_tag_id = self.min_tag_id
    uri = ""

    if (min_tag_id.nil?)
      uri = "https://api.instagram.com/v1/tags/#{self.tag}/media/recent?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b"
      response = HTTParty.get(uri).parsed_response
      if response["pagination"]["min_tag_id"]
        load_posts(response)
        self.save_data_from_api
      else
        return true
      end
    elsif !(min_tag_id.nil?)
      uri = "https://api.instagram.com/v1/tags/#{self.tag}/media/recent?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b&max_tag_id=#{min_tag_id}"
      response = HTTParty.get(uri).parsed_response
      if response["pagination"]["max_tag_id"]
        uri = "https://api.instagram.com/v1/tags/#{self.tag}/media/recent?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b&max_tag_id=#{min_tag_id}"
        response = HTTParty.get(uri).parsed_response
        load_posts(response)
        self.save_data_from_api
      else
        return true
      end
    end
  end

  def load_posts(response)
    data = response["data"]
    data.map do |ipost|
      instagram_post = self.instagram_posts.build
      instagram_post.uid = ipost["caption"]["from"]["id"]
      instagram_post.username = ipost["caption"]["from"]["username"]
      instagram_post.caption = ipost["caption"]["text"]
      instagram_post.created_at = ipost["caption"]["created_time"]
      instagram_post.comments = ipost["comments"]["count"]
      instagram_post.likes = ipost["likes"]["count"]
      instagram_post.link = ipost["link"]
      instagram_post.image = ipost["images"]["standard_resolution"]["url"]
      self.instagram_posts.push(instagram_post)
    end
    self.min_tag_id = response["pagination"]["min_tag_id"]
    self.save
  end
end

app/models/country.rb
class Country < ActiveRecord::Base
  # attr_accessible :title, :body
  has_and_belongs_to_many :campaigns
end

app/models/impression.rb
class Impression < ActiveRecord::Base
  attr_accessible :source, :ambassador_id, :hover_time, :view_time, :city, :country, :ip, :region, :coord

  belongs_to :ambassador
  belongs_to :campaign
end

app/models/instagram_post.rb
class InstagramPost < ActiveRecord::Base
  attr_accessible :uid, :username, :caption, :comments, :likes, :link, :image, :created_at
  belongs_to :campaign
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :users
  has_many :campaigns
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :ambassador
  belongs_to :campaign
end

app/models/social.rb
class Social < ActiveRecord::Base
  belongs_to :user
  # named_scope :by_author, lambda {|author| {:conditions => {:author_id => author.id}}}
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  #scope :role, -> (ambassador_id) { where.not(:mid => Ambassador.select(ambassador_id).uniq) }
  scope :is_influencer, -> { where(role: 'influencer') }
  #scope :interests

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
=begin
  before_validation :assign_roles
  def assign_roles
    puts '#'*100
    puts (role == "influencer")
    self.role = (role == "influencer") ? "influencer":"brand"
  end
=end

  has_many :brands
  has_many :ambassadors
  belongs_to :interest
  has_many :socials
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
	def instagram
		response = HTTParty.get('https://api.instagram.com/oauth/authorize/?client_id=fdaf0607c4c04ac5b0dd5c2e30f56fd3&redirect_uri=http://localhost/ambassadors&response_type=json')
		binding.pry
		puts response
		puts
	end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  layout false
  def index
    @brand = Brand.find(params[:brand_id])
    @campaigns = @brand.campaigns
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @campaign = Campaign.find_by_id(params[:id])
    @ambassadors = @campaign.ambassadors
    @user = current_user
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @campaign = Campaign.find_by_id(params[:id])
    if @campaign.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  def new
    @countries = Country.all
    @brand = Brand.find(params[:brand_id])
    @campaign = @brand.campaigns.build
    @interests = Interest.all
    respond_to do |format|
      format.js
    end
  end

  def create
    @brand = Brand.find(params[:brand_id])
    @campaign = @brand.campaigns.build(campaign_param)
    @campaign.interest_id = params[:campaign][:interest].to_i
    @campaign.countries.push(Country.find_by_iso('GH'))
    puts '#'*100
    puts campaign_param

    respond_to do |format|
      if @campaign.save
        format.js{render "index"}
      else
        format.js{render :new}
      end
    end
  end

  def edit
    @brand = Brand.find(params[:brand_id])
    @campaign = Campaign.find_by_id(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @campaign = Campaign.find(params[:id])
    if @campaign.update_attributes(campaign_param)
      respond_to do |format|
        format.js{render 'show'}
      end
    end
  end

  def stats
    @campaign = Campaign.find(params[:campaign_id])
    @impressions = @campaign.impressions
    @ambassadors = Ambassador.where(campaign_id: @campaign.id, status: 'accepted')
    @reach = 0
    @ambassadors.each do |a|
      @reach += a.user.socials.first.followers.to_i
    end
    respond_to do |format|
      format.js
    end
    @campaign.save_data_from_api
  end

  def invite
    @campaign = Campaign.find(params[:campaign_id])
    @ambassador = Ambassador.new
    @invited = @campaign.ambassadors
    @users = User.find_by_sql("SELECT * FROM users WHERE role = 'influencer' AND id NOT IN (SELECT user_id FROM ambassadors WHERE campaign_id = "+@campaign.id.to_s+") AND id IN (SELECT user_id FROM socials)")
    respond_to do |format|
      format.js
    end
  end

  private
    def campaign_param
      params.require(:campaign).permit(:name, :url, :description, :image, :tag)
    end

    def interest_arr
      params.require(:campaign).permit(interests: [])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
    #redirect_to "http://localhost:9000"
  end

end

app/helpers/ambassadors_helper.rb
module AmbassadorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/_dashboard.html.erb
<!-- WEB -->
Web / Organic Data
<div class="row">
  <!-- Likes -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-info no-margin">
          <strong class="text-xl"><%= @impressions.count %></strong><br/>
          <span class="opacity-50">Impressions</span>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->

  <!-- Comments -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-warning no-margin">
          <strong class="text-xl"><%= @impressions.inject(0){|sum,x| sum + x.view_time } %></strong><br/>
          <span class="opacity-50">View (sec)</span>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->

  <!-- Likes per Impression -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-danger no-margin">
          <strong class="text-xl"><%= @impressions.inject(0){|sum,x| sum + x.hover_time } %></strong><br/>
          <span class="opacity-50">Hover (sec)</span>

        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->

  <!-- Cost per Impression -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-success no-margin">

          <strong class="text-xl"><%= ((@impressions.inject(0){|sum,x| sum + x.view_time }) / (@impressions.count == 0 ? 1 : @impressions.count)) %></strong><br/>
          <span class="opacity-50">View (sec) per Impression</span>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->
</div><!--end .row -->
<!-- WEB END -->
<!-- SOCIAL -->
<hr>
Social Statistics
<div class="row">
  <!-- Likes -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-info no-margin">

          <strong id="noOfPosts" class="text-xl"><%= @reach %></strong><br/>
          <span class="opacity-50">Reach</span>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->

  <!-- Comments -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-warning no-margin">
          <strong class="totalLikes text-xl">901</strong><br/>
          <span class="opacity-50">Likes</span>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->

  <!-- Likes per Impression -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-danger no-margin">
          <strong class="totalComments text-xl">345</strong><br/>
          <span class="opacity-50">Comments</span>

        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->

  <!-- Likes per Reach -->
  <div class="col-md-3 col-sm-6">
    <div class="card">
      <div class="card-body no-padding">
        <div class="alert alert-callout alert-success no-margin">

          <strong class="text-xl">6.9%</strong><br/>
          <span class="opacity-50">Likes per Reach</span>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->
</div><!--end .row -->
<!-- SOCIAL END -->

<div class="row">

  <!-- Campaign Trend -->
  <div class="col-md-9">
    <div class="card ">
      <div class="row">
        <div class="col-md-8">
          <div class="card-head">
            <header>Campaign Trend</header>
          </div><!--end .card-head -->
          <div class="card-body height-8">
            <div id="flot-visitors-legend" class="flot-legend-horizontal stick-top-right no-y-padding"></div>
            <div id="flot-visitors" class="flot height-7" data-title="Activity entry" data-color="#7dd8d2,#0aa89e"></div>
          </div><!--end .card-body -->
        </div><!--end .col -->
        <div class="col-md-4">
          <div class="card-head">
            <header>Today's stats</header>
          </div>
          <div class="card-body height-8">
            <strong>214</strong> members
            <span class="pull-right text-success text-sm">0,18% <i class="md md-trending-up"></i></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:43%"></div>
            </div>
            756 pageviews
            <span class="pull-right text-success text-sm">0,68% <i class="md md-trending-up"></i></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:11%"></div>
            </div>
            291 bounce rates
            <span class="pull-right text-danger text-sm">21,08% <i class="md md-trending-down"></i></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-danger" style="width:93%"></div>
            </div>
            32,301 visits
            <span class="pull-right text-success text-sm">0,18% <i class="md md-trending-up"></i></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:63%"></div>
            </div>
            132 pages
            <span class="pull-right text-success text-sm">0,18% <i class="md md-trending-up"></i></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:47%"></div>
            </div>
          </div><!--end .card-body -->
        </div><!--end .col -->
      </div><!--end .row -->
    </div><!--end .card -->
  </div><!--end .col -->
  <!-- END SITE ACTIVITY -->

  <!-- View Comments -->
  <div class="col-md-3">
    <div class="card">
      <div class="card-head">
        <header class="text-primary">Comments</header>
      </div><!--end .card-head -->
      <div class="card-body height-4">
        <div class="pull-right text-center">

        </div>
      </div><!--end .card-body -->
      <div class="card-body height-4 no-padding">

      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->

</div>

<script>
    console.log("Fetching data from instagram");
    var hashtag = "<%= @campaign.tag %>";
    //var hashtag = "hashtag";
    console.log("Hashcode: " + hashtag);
    var totalLikes = 0;
    var totalComments = 0;
    var postsCount = 0;
    console.log(hashtag);
    //Getting likes & comments INSTAGRAM API
    $.ajax({
        type: 'GET',
        dataType: 'jsonp',
        url: "https://api.instagram.com/v1/tags/" + hashtag + "/media/recent?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b&count=33",
        success: function(data) {
            postsCount += data.data.length;
            $('#noOfPosts').text(data.data.media_count);
            for (var i = 0; i < data.data.length; i++) {
                totalLikes += data.data[i].likes.count;
                totalComments += data.data[i].comments.count;
            }
            if (data.pagination.next_url === undefined) {
                $('.totalLikes').text(totalLikes);
                $('.totalComments').text(totalComments);
            } else {
                $('.totalLikes').text(totalLikes);
                $('.totalComments').text(totalComments);
                getNextPosts(data.pagination.next_url, totalLikes, totalComments, postsCount);
            }
        }
    });

    function getNextPosts(url, likes, comments, count) {
        $.ajax({
            type: 'GET',
            dataType: 'jsonp',
            url: url,
            success: function(nxtData) {
                var newUrl = nxtData.pagination.next_url;
                if (newUrl === undefined) {
                    count += nxtData.data.length;
                    for (var i = 0; i < nxtData.data.length; i++) {
                        likes += nxtData.data[i].likes.count;
                        comments += nxtData.data[i].comments.count;
                    }
                    $('.totalLikes').text(likes);
                    $('.totalComments').text(comments);
                    console.log("last posts request");
                } else {
                    count += nxtData.data.length;
                    console.log(Math.round(count/nxtData.data.length)+ " requests")
                    for (var i = 0; i < nxtData.data.length; i++) {
                        likes += nxtData.data[i].likes.count;
                        comments += nxtData.data[i].comments.count;
                    }
                    $('.totalLikes').text(likes);
                    $('.totalComments').text(comments);
                    getNextPosts(newUrl, likes, comments, count);
                }
            }
        });
    }
</script>

app/views/campaigns/_edit.html.erb
<script>
    $(document).ready(function () {
        $('#hashtag').on('keyup', function() {
            console.log("dfdjfhdjfhdjfhdjfhd;iodsioudiofubn");
            if ($('#hashtag').val().length > 2){
                var hashtag = $('#hashtag').val();
                console.log("H: "+hashtag);
                //getting the number of posts under a hashtags
                $.ajax({
                    type: 'GET',
                    dataType: 'jsonp',
                    url: "https://api.instagram.com/v1/tags/" + hashtag + "?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b",
                    success: function(data) {
                        if (data.data.media_count === 0){
                            // turn green and enable submit
                            good();
                        }else {
                            // turn red and disable submit
                            bad();
                        }
                    }
                });
            }else{
                // turn red or disable button
                bad();
            };
        });

        function good(){
            console.log('good');
            $("#submit").prop('disabled', false);
            $("#hash-circle").css('background','green');
        }

        function bad(){
            console.log('bad');
            $("#submit").prop('disabled', true);
            $("#hash-circle").css('background','red');
        }
    });

</script>
<div>
  Edit your campaign

  <%= form_for [@brand, @campaign], html: {multipart: true, method: :put}, remote: true do |f|%>
      <div class="form-group floating-label spacing">
        <%= f.text_field :name, value: @campaign.name, size: '80', class: "form-control", placeholder: "Campaign name", require:''%>
        <label></label>
      </div>
      <div class="form-group floating-label spacing">
        <%= f.text_field :url, value: @campaign.url, size: '80', class: "form-control", placeholder: "Campaign URL", required:''%><label></label>
      </div>
      <div class="form-group mui-textfield hashtag">
        <div id="hash-circle" class="circle float-top-right"></div>
        <%= f.text_field :tag, value: @campaign.tag, size: '80', placeholder: "Campaign #hashtag", id: "hashtag", class: "form-control form-group"%>
        <label></label>
      </div>
      <div class="form-group floating-label spacing">
        <%= f.text_area :description, value: @campaign.description, size: '80', class: "form-control", placeholder: "Description" %><label></label>
      </div>

      <br>

      <div class="form-group">
        <%= f.file_field :image %>
      </div>

      <div class="form-group floating-label spacing">
        <%= f.submit 'Update Campaign' , class:"btn ink-reaction btn-lg btn-accent cload", id: "submit" %>
      </div>
  <% end %>
</div>

app/views/campaigns/_index.html.erb
<div class="col-md-10 col-md-offset-1">
<div class="card card-outline style-accent">
  <div class="card-head">
   <header> <div class="section-header">
    <ol class="breadcrumb">
      <li class="active"><%= link_to ({:action=>"index", :controller=>"brands", remote: true}) do %>
       Brands
       <% end %>/ <span style="color:#ffffff;font-weight:bold"><%= brand.name %></span></li>
     </ol>
   </div></header>
   <div class="tools">
    <%= link_to "/brands/#{brand.id}/campaigns/new", remote: true do %>
    <div class="btn btn-raised btn-primary cload"><i class="fa fa-plus"> </i> Add Campaign</div>
    <% end %>
    <!-- <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a> -->
  </div>
</div>
<div class="white no-pad">
<div class="row">
  <% if brand.campaigns.length == 0 %>
    <%= render "campaigns/zero", brand: brand %>
  <% else %>
     <% brand.campaigns.each do |c| %>
        <div id="card-<%= c.id %>">
        <%= link_to "/brands/#{c.brand_id}/campaigns/#{c.id}", remote: true do %>
            <div class="card col-md-4">
              <div class="col-xs-10 cload"><%= c.name %></div>
              <%= link_to "/brands/#{c.brand_id}/campaigns/#{c.id}", method: :delete, remote: true do %>
                  <div class="col-xs-2 cdelete cload">
                    <i class="fa fa-trash"></i></div>
              <% end %>
            </div>
        <% end %>
        </div>
     <% end %>
  <% end %>
</div>
</div>

</div>
</div>

app/views/campaigns/_invite.html.erb
These are the Influencers that can push your business to the next level
<% if !@invited.empty? %>
    <%= render 'invited' %>
<% end %>
<span class="row">
  <% @users.each do |u| %>
      <div id="user_card_<%= u.id %>" class="card cprofile col-sm-6 ov-hidden small-pad">
        <% instag = u.socials.where(provider: 'instagram').first %>
        <div class="ctitle"><%= instag.username %></div>
        <div class="row">
          <div class="col-sm-6">
            <%= image_tag instag.photo, class:'circle shad px100'%>
          </div>
          <div class="col-sm-6 pad-none ov-hidden">
            <div>
              <%= u.email %>
            </div>
            <div>
              <%= instag.followers + " followers" %>
            </div>
            <%= form_for ambassador, :url => {controller: 'ambassadors', action: 'create'}, remote: true do |f|%>
                <%= f.hidden_field :user_id, value: u.id %>
                <%= f.hidden_field :campaign_id, value: @campaign.id %>
                <%= f.hidden_field :status, value: 'pending' %>
                <%= button_tag(type: 'submit', alt: 'invite', class: 'btn btn-primary') do %>
                    invite
                <% end %>
            <% end %>
          </div>
        </div>

      </div>
  <% end %>
</span>

app/views/campaigns/_show.html.erb
<div class="col-md-7 col-md-offset-3">
  <div class="card brand-accent">
    <% if current_user.id == @campaign.brand.user_id %>
        <%= render 'top_mini_menu' %>
        <div class="card-head">
            <%= link_to brand_campaigns_path(@campaign.brand), remote: true do %>
                <span class="cload"><i class="fa fa-arrow-left"></i> Back</span>
            <% end %>
            <div class="tools">
                  <%= link_to  edit_brand_campaign_path(@campaign.brand_id, @campaign.id), remote: true do %>
                      <span class="cload"><i class="fa fa-pencil"></i> Edit</span>
                  <% end %>

            </div>
        </div>
    <% end %>
    <div class="white no-pad">
      <div id="show_inner">
        <div class="row">
          <div class="col-md-6">
            <div class="field">
              <div class="ftitle">Name</div>
              <%= @campaign.name%>
            </div>

            <div class="field">
              <div class="ftitle">Campaign weblink</div>
              <%= @campaign.url%>
            </div>

            <div class="field">
              <div class="ftitle">Socail Hashtag</div>
              #<%= @campaign.tag%>
            </div>

            <div class="field">
              <div class="ftitle">Description</div>
              <%= @campaign.description%>
            </div>
          </div>
          <div class="col-md-6">
            <div class="field">
              <div class="ftitle">Campaign photo</div>
              <% if @campaign.image.url %>
                <%= image_tag @campaign.image.url, class: 'cphoto' %>
              <% else %>
                No image uploaded
              <% end %>
            </div>
          </div>
        </div>

        <% if (user.role == 'influencer') %>
            <div class="embed no-pad">
                <% amb = Ambassador.where(user_id: user.id, campaign_id: @campaign.id).first %>
                <% if amb.status == "accepted" %>
                    Copy the following
                    <hr/>
                    <div>URL (link)</div>
                    http://swayup.co/ambassadors/<%= amb.id %>/redirect
                    <hr>
                    <div>Social</div>
                    #<%= @campaign.tag %>
                    <hr>
                    <div>Embed code</div>
                    <pre><code>&lt;div class=&quot;pry_card card&quot;&gt;&lt;/div&gt;&lt;script&gt;var ambid=<%= amb.id %>;var script = document.createElement('script');script.src = "geo.js";document.head.appendChild(script);&lt;/script&gt;
                        </code>
                    </pre>
                <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/_top_mini_menu.html.erb
<div class="row center link-white">
  <%= link_to  brand_campaign_path(@campaign.brand_id, @campaign.id), remote: true do %>
    <div id="campaign_view" class="col-sm-4 c-inactive cload">View</div>
  <% end %>
  <%= link_to  brand_campaign_stats_path(@campaign.brand_id, @campaign.id), remote: true do %>
    <div id="campaign_stats" class="col-sm-4 cload">Stats</div>
  <% end %>
  <%= link_to  brand_campaign_invite_path(@campaign.brand_id, @campaign.id), remote: true do %>
    <div id="campaign_invite" class="col-sm-4 cload">Invite</div>
  <% end %>
</div>

app/views/campaigns/_zero.html.erb
<div class="row">
  <div class="col-md-5">
    <%= image_tag 'campaign_zero.png' , class: 'zero' %><br>
    
  </div>
  <div class="col-md-7 center">
    <span class="zero-main">Your unique campaign will be powered by our Influencers</span><br><br>
     <span class="zero-sub">Click
       <%= link_to "/brands/#{brand.id}/campaigns/new", remote: true do %>
        <div class="btn btn-primary cload">Add campaign</div>
       <% end %> to Sway <b><i><%= brand.name %></i></b> Up</span>

  </div>
</div>

app/views/campaigns/destroy.js.erb
$("#card-<%= @campaign.id %>").hide("slow").delay(1000).remove();
$("#jloader").delay(1000).fadeOut("slow");

app/views/campaigns/edit.js.erb
$("#show_inner").html("<%= escape_javascript(render 'campaigns/edit', campaign: @campaign) %>");
$("#jloader").delay(1000).fadeOut("slow");

app/views/campaigns/invite.js.erb
$('#campaign_view, #campaign_stats').removeClass('c-inactive');
$('#campaign_invite').addClass('c-inactive');
$("#show_inner").html("<%= escape_javascript(render 'campaigns/invite', campaign: @campaign, ambassador: @ambassador, users: @users) %>");
$("#jloader").delay(1000).fadeOut("slow");

app/views/campaigns/stats.js.erb
$('#campaign_view, #campaign_invite').removeClass('c-inactive');
$('#campaign_stats').addClass('c-inactive');
$("#show_inner").html("<%= escape_javascript(render 'campaigns/dashboard') %>");
$("#jloader").delay(1000).fadeOut("slow");