config/routes.rb
Influence::Application.routes.draw do
	devise_for :users
	resources :users
  resources :ambassadors do
    resources :impressions
    resources :leads
  end
  get '/ongoing_list', to: 'ambassadors#ongoing_list'
  get '/ambassadors/campaigns', to: 'ambassadors#campaigns'
  get '/instagram_redirect', to: 'ambassadors#instagram_redirect', as: :instagram_redirect

  get '/users/sign_in?role=influencer', to: 'devise/sessions#new'
  get '/brand_list', to: 'brands#brand_list'
  resources :brands do

    resources :campaigns do
      get '/invite', to: 'campaigns#invite'
      get '/stats', to: 'campaigns#stats'
    end
  end

  root :to => 'home#index'
end

app/models/ambassador.rb
class Ambassador < ActiveRecord::Base
  attr_accessible :user_id, :campaign_id, :status
  belongs_to :user
  belongs_to :campaign
  has_many   :leads
  has_many   :impressions
  has_many   :ambassador_requests
end

app/models/ambassador_request.rb
class AmbassadorRequest < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :ambassador
  belongs_to :campaign
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true
  validates :description,  presence: true

  has_many :campaigns
  belongs_to :user

  attr_accessible :name, :description
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :brand
  has_many :ambassadors
  has_and_belongs_to_many :countries
  belongs_to :interest
  has_many   :ambassador_requests
  has_many :impressions, through: :ambassadors
  mount_uploader :image, ImageUploader
  has_many :instagram_posts

  attr_accessible :name, :description, :url, :country_ids, :interest, :image, :tag

  def save_data_from_api
    min_tag_id = self.min_tag_id
    uri = ""

    if (min_tag_id.nil?)
      uri = "https://api.instagram.com/v1/tags/#{self.tag}/media/recent?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b"
      response = HTTParty.get(uri).parsed_response
      if response["pagination"]["min_tag_id"]
        load_posts(response)
        self.save_data_from_api
      else
        return true
      end
    elsif !(min_tag_id.nil?)
      uri = "https://api.instagram.com/v1/tags/#{self.tag}/media/recent?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b&max_tag_id=#{min_tag_id}"
      response = HTTParty.get(uri).parsed_response
      if response["pagination"]["max_tag_id"]
        uri = "https://api.instagram.com/v1/tags/#{self.tag}/media/recent?access_token=806401368.5aa13be.4a08df065cbb41469c9cc20041432d3b&max_tag_id=#{min_tag_id}"
        response = HTTParty.get(uri).parsed_response
        load_posts(response)
        self.save_data_from_api
      else
        return true
      end
    end
  end

  def load_posts(response)
    data = response["data"]
    data.map do |ipost|
      instagram_post = self.instagram_posts.build
      instagram_post.uid = ipost["caption"]["from"]["id"]
      instagram_post.username = ipost["caption"]["from"]["username"]
      instagram_post.caption = ipost["caption"]["text"]
      instagram_post.created_at = ipost["caption"]["created_time"]
      instagram_post.comments = ipost["comments"]["count"]
      instagram_post.likes = ipost["likes"]["count"]
      instagram_post.link = ipost["link"]
      instagram_post.image = ipost["images"]["standard_resolution"]["url"]
      self.instagram_posts.push(instagram_post)
    end
    self.min_tag_id = response["pagination"]["min_tag_id"]
    self.save
  end
end

app/models/country.rb
class Country < ActiveRecord::Base
  # attr_accessible :title, :body
  has_and_belongs_to_many :campaigns
end

app/models/impression.rb
class Impression < ActiveRecord::Base
  attr_accessible :source, :ambassador_id, :hover_time, :view_time, :city, :country, :ip, :region, :coord

  belongs_to :ambassador
  belongs_to :campaign
end

app/models/instagram_post.rb
class InstagramPost < ActiveRecord::Base
  attr_accessible :uid, :username, :caption, :comments, :likes, :link, :image, :created_at
  belongs_to :campaign
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :users
  has_many :campaigns
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :ambassador
  belongs_to :campaign
end

app/models/social.rb
class Social < ActiveRecord::Base
  belongs_to :user
  # named_scope :by_author, lambda {|author| {:conditions => {:author_id => author.id}}}
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  #scope :role, -> (ambassador_id) { where.not(:mid => Ambassador.select(ambassador_id).uniq) }
  scope :is_influencer, -> { where(role: 'influencer') }
  #scope :interests

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
=begin
  before_validation :assign_roles
  def assign_roles
    puts '#'*100
    puts (role == "influencer")
    self.role = (role == "influencer") ? "influencer":"brand"
  end
=end

  has_many :brands
  has_many :ambassadors
  belongs_to :interest
  has_many :socials
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
	def instagram
		response = HTTParty.get('https://api.instagram.com/oauth/authorize/?client_id=fdaf0607c4c04ac5b0dd5c2e30f56fd3&redirect_uri=http://localhost/ambassadors&response_type=json')
		binding.pry
		puts response
		puts
	end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  layout false
  def index
    if (!current_user)
      redirect_to "/"
    else
      @brands = current_user.brands
      @user_id = current_user.id
      puts '#'*100
      puts @brands
    end
  end

  def brand_list
    @brands = current_user.brands
    puts '~'*100
    puts @brands
    respond_to do |format|
      format.js{render "index"}
    end
  end

  def new
    @brand = Brand.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @brand = Brand.new(brand_param)
    @brand.user_id = current_user.id
    respond_to do |format|
      if @brand.save
        @brands = current_user.brands
        format.js { render "index"}
      else
        format.js { render "error"}
      end
    end
  end

  def show
    @brand = Brand.find_by_id(params[:id])
    @campaigns = Campaign.find_all_by_brand_id(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @brand = Brand.find_by_id(params[:id])
    if @brand.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  private
    def brand_param
      params.require(:brand).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
    #redirect_to "http://localhost:9000"
  end

end

app/helpers/ambassadors_helper.rb
module AmbassadorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/_brand_list.html.erb
<div class="card card-outline" style="border:1px solid purple">
    <ul>Brands
      <% brands.each do |b| %>
          <li>
            <%= link_to ({action: "index", controller: "campaigns", brand_id: b.id, remote: true}) do %>
                <%= b.name %><br>
            <% end %>
          </li>
      <% end %>
    </ul>
</div>

app/views/brands/_index.html.erb
<div class="card card-outline">
    Brands
    <% brands.each do |b| %>
      <div id="card-<%= b.id %>">
        <%= link_to ({action: "index", controller: "campaigns", brand_id: b.id, remote: true}) do %>
            <div class="card col-md-4">
              <div class="col-xs-10"><%= b.name %></div>
              <%= link_to "/brands/#{b.id}", method: :delete, remote: true do %>
                  <div class="col-xs-2 cdelete cload">
                    <i class="fa fa-trash"></i></div>
              <% end %>
            </div>
        <% end %>
      </div>
    <% end %>
</div>

app/views/brands/_new.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="card card-outline style-accent">
  <div class="card-head">
  <h1 class="text-center">Create a new brand</h1>
</div>
<div class="white no-pad">
  <%= form_for @brand, remote: true do |f|%>
    <div class="form-group floating-label spacing">
      <%= f.text_field :name, size: '80', class:"form-control" %>
      <label>Name</label>
    </div>
    <div class="form-group floating-label spacing">
      <%= f.text_field :description, size: '80', class:"form-control"%>
      <label>Description</label>
    </div>
    <div class="form-group floating-label spacing">
      <%= f.submit 'Create Brand' , class:"btn ink-reaction btn-lg btn-accent" %>
    </div>

<% end %>

  <div id="cerror"></div>
</div>
</div>
</div>

app/views/brands/_show.html.erb
    <div class="card card-outline">
        <div class="row"></div>
        <div class="card-head">
          <%= link_to ({:action=>"index", :controller=>"brands", remote: true}) do %>
              < Back
          <% end %>
          <header><%= brand.name %></header>
          <div class="tools">
          <%= link_to "/brands/#{brand.id}/campaigns/new" do %>
            <div class="btn btn-primary"><i class="fa fa-plus"></i> Add Campaign</div>
        <% end %>
        <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
        </div>
        </div>
        <div class="row">
            <% if brand.campaigns.length == 0 %>
              <div class="card col-offset-4 col-md-4">
                You have not created any campaigns
              </div>
            <% else %>
                <% brand.campaigns.each do |c| %>
                  <div>
                      <%= link_to "/brands/#{c.brand_id}/campaigns/#{c.id}" do %>
                          <div class="card col-md-4">
                            <div class="ctop">...</div>
                            <div class="cmid"><%= c.name %></div>

                          </div>
                      <% end %>
                <% end %>
            <% end %>
        </div>
        </div>
    </div>

app/views/brands/_side_bar.html.erb
<div id="menubar" class="menubar-inverse">
  <div class="menubar-fixed-panel">
    <div>
      <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
        <i class="fa fa-bars"></i>
      </a>
    </div>
    <div class="expanded">
      <a href="#">
        <span class="text-lg text-bold text-accent">Sway&nbsp;Up</span>
      </a>
    </div>
  </div>
  <div class="menubar-scroll-panel">

    <!-- BEGIN MAIN MENU -->
    <ul id="main-menu" class="gui-controls">

      <!-- BEGIN DASHBOARD -->
      <li>
        <a href="#" class="active">
          <div class="gui-icon"><i class="fa fa-home"></i></div>
          <span class="title">Brand Tracker</span>
        </a>
      </li><!--end /menu-li -->
      <!-- END DASHBOARD -->

      <!-- BEGIN DASHBOARD -->
      <li>
        <%= link_to ({:action=>"new", :controller=>"brands", remote: true}) do %>
        <div class="gui-icon"><i class="fa fa-plus fa-fw"></i></div>
        <span class="title">Create Brand</span>
        <% end %>
      </li><!--end /menu-li -->
      <!-- END DASHBOARD -->
      <li>
        <a href="#">
          <div class="gui-icon"><i class="fa fa-line-chart"></i></div>
          <span class="title">Live Campaigns</span>
        </a>
      </li>
      <li>
        <%= link_to brand_list_path, class: "cload", remote: true do%>
          <div class="gui-icon"><i class="fa fa-globe"></i></div>
          <span class="title">All Brands</span>
        <% end %>
      </li>
      <li>
        <a href="#">
          <div class="gui-icon"><i class="fa fa-volume-up"></i></div>
          <span class="title">All Campaigns</span>
        </a>
      </li>
    </ul><!--end .main-menu -->
    <!-- END MAIN MENU -->

    <div class="menubar-foot-panel">
      <small class="no-linebreak hidden-folded">
        <span class="opacity-75">Copyright &copy; 2016</span> <strong>SwayUp</strong>
      </small>
    </div>
  </div><!--end .menubar-scroll-panel-->
</div><!--end #menubar-->

app/views/brands/_top_bar.html.erb
<div class="headerbar">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="headerbar-left">
    <ul class="header-nav header-nav-options">
      <li class="header-nav-brand" >
        <div class="brand-holder">
          <div class="logo">
             <a href="/">
            <span class="text-lg text-bold text-primary">Sway Up</span>
          </a>
          </div>
        </div>
      </li>
      <li>
        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
          <i class="fa fa-bars"></i>
        </a>
      </li>
      <li>
        <%= link_to ({:action=>"new", :controller=>"brands", remote: true}) do %>
            <button type="button" class="btn ink-reaction btn-primary">
              <i class="fa fa-plus"></i> &nbsp; Brand</button>
        <% end %>
      </li>

    </ul>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="headerbar-right">
    <ul class="header-nav header-nav-options">
      <li>
        <!-- Search form -->
        <form class="navbar-search" role="search">
          <div class="form-group">
            <input type="text" class="form-control" name="headerSearch" placeholder="Search ">
          </div>
          <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
        </form>
      </li>
    </ul><!--end .header-nav-options -->
    <ul class="header-nav header-nav-profile">
      <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
          <%= image_tag('chiamaka.jpg') %>
          <span class="profile-info">
                    Daniel Johnson
                    <small>Coca Cola</small>
                  </span>
        </a>
        <ul class="dropdown-menu animation-dock" role="menu">
          <li><a href="#"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
        </ul>
      </li>
    </ul><!--end .header-nav-profile -->
  </div><!--end #header-navbar-collapse -->
</div>

app/views/brands/_zero.html.erb
<div class="card card-outline row" style="border:1px solid purple">
  <div class="col-lg-5 col-md-6">
    <%= image_tag 'brand_zero.png' , class: 'zero' %>
  </div>
  <div class="col-lg-7 col-md-6 center">
    <span class="zero-main">Leverage on our Influencer platform to build your brand</span><br>
    <span class="zero-sub">Click on <strong>"Add brand"</strong> to create one</span><br>
    <%= link_to ({:action=>"new", :controller=>"brands", remote: true}) do %>
        <div class="btn btn-primary">Add brand</div>
    <% end %>
  </div>
</div>

app/views/brands/destroy.js.erb
$("#card-<%= @brand.id %>").hide("slow");

app/views/brands/error.js.erb
$("#cerror").html("Error - Please fill the required fields")

app/views/brands/index.js.erb
$("#content section .section-body").html("<%= escape_javascript(render 'brands/index', brands: @brands) %>");
$("#jloader").delay(1000).fadeOut("slow");

app/views/brands/new.html.erb
<div class="card-head style-accent">
	<h1>Create a new brand</h1>
</div>
<div class="card-body">
	<%= form_for @brand do |f|%>
    <div class="field">
      <%= f.text_field :name, size: '80', placeholder: "Brand name"%>
    </div>
    <div class="field">
      <%= f.text_field :description, size: '80', placeholder: "Description"%>
    </div>
    <div class="field">
      <%= f.submit %>
    </div>

<% end %>

</div>

app/views/brands/new.js.erb
$("#content section .section-body").html("<%= escape_javascript(render 'brands/new', brand: @brand) %>")

app/views/brands/show.html.erb
<h1>Brands#show</h1>
<h1>Brand name: <%= @brand.name %></h1>
<% if @campaigns.length == 0 %>
    You have not created any campaigns
<% else %>
    <% @campaigns.each do |c| %>
        <%= link_to c.name, brand_campaign_path(c) %><br>
    <% end %>
<% end %>

<%= link_to "/brands/#{@brand.id}/campaigns/new" do %>
    <div class="btn btn-primary"><i class="fa fa-plus"></i> Add Campaign</div>
<% end %>

app/views/brands/show.js.erb
$("#content").html("<%= escape_javascript(render 'brands/show', brand: @brand) %>")